#!/usr/bin/env python3
"""SVG -> LVGL polyline emitter.

Reads a stroke-style SVG (icons, glyphs) and emits a header-only C++ file
that draws each subpath as an `lv_line` widget under a transparent root
container. Fills, paints, dash patterns, and per-element strokes from the
SVG are intentionally ignored -- the caller passes color and stroke width
at draw time. This keeps the LVGL output small and lets a single icon be
re-tinted to match the live confidence-tier color without re-generating.

Dependency: pip install svgelements

Usage:
    python tools/svg_to_lvgl.py icon.svg --name coffee_cup \\
        --out components/ui/include/icons/coffee_cup_icon.hpp

Then in C++:
    lv_obj_t* icon = svg_icon::create_coffee_cup(parent, kColorAccent);
    lv_obj_align(icon, LV_ALIGN_CENTER, 0, 0);
"""

import argparse
import sys

try:
    from svgelements import SVG, Path, Move, Line, Close
except ImportError:
    sys.stderr.write("missing dep -- run: pip install svgelements\n")
    sys.exit(1)


def flatten_segment(seg, tol):
    """Sample one path segment into (x, y) points.

    Lines/Closes contribute their endpoint. Curved segments (Cubic, Quad,
    Arc) get uniform-arc-length sampling at n = len/tol steps. Uniform
    (not adaptive) is fine for typical UI icons at 466x466; swap in
    de Casteljau adaptive splitting if you ever see visible facets on
    long sweeping curves.
    """
    if isinstance(seg, Move):
        return
    if isinstance(seg, (Line, Close)):
        yield (seg.end.x, seg.end.y)
        return
    n = max(2, int(round(seg.length() / max(tol, 0.25))))
    for i in range(1, n + 1):
        p = seg.point(i / n)
        yield (p.x, p.y)


def collect_subpaths(svg_path, tol):
    """Walk one <path> element's segments into a list of polylines.

    A new Move command starts a fresh subpath; everything else extends
    the current one. Subpaths with fewer than two points are dropped.
    """
    out = []
    current = None
    for seg in svg_path:
        if isinstance(seg, Move):
            if current is not None and len(current) >= 2:
                out.append(current)
            current = [(seg.end.x, seg.end.y)]
        else:
            if current is None:
                current = [(seg.start.x, seg.start.y)]
            for pt in flatten_segment(seg, tol):
                current.append(pt)
    if current is not None and len(current) >= 2:
        out.append(current)
    return out


def emit(name, subpaths, vb_w, vb_h, out):
    w = out.write
    w("// Auto-generated by tools/svg_to_lvgl.py -- do not edit by hand.\n")
    w("#pragma once\n\n")
    w('#include "lvgl.h"\n\n')
    w("namespace svg_icon {\n\n")

    for i, sp in enumerate(subpaths):
        w(f"static const lv_point_precise_t {name}_path{i}[] = {{\n")
        for x, y in sp:
            w(f"  {{{int(round(x))}, {int(round(y))}}},\n")
        w("};\n\n")

    w(f"// Create the {name} icon under `parent`. Returned container is\n")
    w(f"// sized to the source viewBox ({vb_w}x{vb_h}); caller positions it\n")
    w("// with lv_obj_set_pos / lv_obj_align.\n")
    w(f"inline lv_obj_t* create_{name}(lv_obj_t* parent,\n")
    w("                                lv_color_t color,\n")
    w("                                int32_t stroke_width = 2) {\n")
    w("  lv_obj_t* root = lv_obj_create(parent);\n")
    w(f"  lv_obj_set_size(root, {vb_w}, {vb_h});\n")
    w("  lv_obj_set_style_bg_opa(root, LV_OPA_TRANSP, LV_PART_MAIN);\n")
    w("  lv_obj_set_style_border_width(root, 0, LV_PART_MAIN);\n")
    w("  lv_obj_set_style_pad_all(root, 0, LV_PART_MAIN);\n")
    w("  lv_obj_remove_flag(root, LV_OBJ_FLAG_SCROLLABLE);\n")
    for i in range(len(subpaths)):
        w(f"  lv_obj_t* l{i} = lv_line_create(root);\n")
        w(f"  lv_line_set_points(l{i}, {name}_path{i},\n")
        w(f"                     sizeof({name}_path{i}) / sizeof({name}_path{i}[0]));\n")
        w(f"  lv_obj_set_style_line_color(l{i}, color, LV_PART_MAIN);\n")
        w(f"  lv_obj_set_style_line_width(l{i}, stroke_width, LV_PART_MAIN);\n")
        w(f"  lv_obj_set_style_line_rounded(l{i}, true, LV_PART_MAIN);\n")
    w("  return root;\n")
    w("}\n\n")
    w("}  // namespace svg_icon\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("svg_file")
    ap.add_argument("--name", required=True,
                    help="C identifier; function becomes create_<name>")
    ap.add_argument("--tol", type=float, default=0.5,
                    help="Flatten tolerance in SVG units (default 0.5)")
    ap.add_argument("--out", default="-",
                    help="Output .hpp path; '-' for stdout (default)")
    args = ap.parse_args()

    # reify=True bakes all <g>/element transforms onto the geometry so
    # every point we read is already in viewBox coordinates.
    svg = SVG.parse(args.svg_file, reify=True)
    vb = svg.viewbox
    if vb is None:
        sys.stderr.write("SVG has no viewBox -- set one in the source.\n")
        sys.exit(1)
    vb_w = int(round(vb.width))
    vb_h = int(round(vb.height))

    subpaths = []
    for elt in svg.elements():
        if isinstance(elt, Path):
            subpaths.extend(collect_subpaths(elt, args.tol))

    if not subpaths:
        sys.stderr.write("No drawable <path> elements found.\n")
        sys.exit(1)

    if args.out == "-":
        emit(args.name, subpaths, vb_w, vb_h, sys.stdout)
    else:
        with open(args.out, "w") as f:
            emit(args.name, subpaths, vb_w, vb_h, f)
    sys.stderr.write(
        f"emitted {len(subpaths)} subpath(s), "
        f"{sum(len(s) for s in subpaths)} point(s) total\n")


if __name__ == "__main__":
    main()
